
enum EVENT_TYPES {
	
	PLAYER_MOVE_BY_BUTTON__START = "PLAYER-MOVE-BY-BUTTON::START",
	PLAYER_MOVE_BY_BUTTON__COMPLETE = "PLAYER-MOVE-BY-BUTTON::COMPLETE",

	PLAYER_MOVE_BY_DRAG__START = "PLAYER-MOVE-BY-DRAG::START",
	PLAYER_MOVE_BY_DRAG__COMPLETE = "PLAYER-MOVE-BY-DRAG::COMPLETE",

}